package com.mnuo.brieflife.entity;
// Generated 2016-10-22 19:54:50 by Hibernate Tools 5.2.0.Beta1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BlBill generated by hbm2java
 */
@Entity
@Table(name = "bl_bill", catalog = "brieflife")
public class BlBill implements java.io.Serializable {
	private static final long serialVersionUID = -7176580914837654845L;
	private Integer id;
	private BlUser blUser;
	private Integer type;
	private String descript;
	private BigDecimal account;
	private Date recordAt;
	private Date createdAt;

	public BlBill() {
	}

	public BlBill(BlUser blUser, BigDecimal account) {
		this.blUser = blUser;
		this.account = account;
	}

	public BlBill(BlUser blUser, Integer type, String descript, BigDecimal account, Date recordAt, Date createdAt) {
		this.blUser = blUser;
		this.type = type;
		this.descript = descript;
		this.account = account;
		this.recordAt = recordAt;
		this.createdAt = createdAt;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public BlUser getBlUser() {
		return this.blUser;
	}

	public void setBlUser(BlUser blUser) {
		this.blUser = blUser;
	}

	@Column(name = "type")
	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	@Column(name = "descript")
	public String getDescript() {
		return this.descript;
	}

	public void setDescript(String descript) {
		this.descript = descript;
	}

	@Column(name = "account", nullable = false, precision = 18)
	public BigDecimal getAccount() {
		return this.account;
	}

	public void setAccount(BigDecimal account) {
		this.account = account;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "record_at", length = 19)
	public Date getRecordAt() {
		return this.recordAt;
	}

	public void setRecordAt(Date recordAt) {
		this.recordAt = recordAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

}
