package com.mnuo.brieflife.entity;
// Generated 2016-10-23 10:26:21 by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BlImageMessage generated by hbm2java
 */
@Entity
@Table(name = "bl_image_message", catalog = "brieflife")
public class BlImageMessage extends BaseMessage implements java.io.Serializable {
	private static final long serialVersionUID = -9131797776795147810L;
	private Integer id;
	private String picUrl;
	private String mediaId;

	public BlImageMessage() {
	}

	public BlImageMessage(BlPosition blPosition, String fromUserName, Date createTime, String msgType, String picUrl,
			String mediaId, String msgId) {
		this.blPosition = blPosition;
		this.fromUserName = fromUserName;
		this.createTime = createTime;
		this.msgType = msgType;
		this.picUrl = picUrl;
		this.mediaId = mediaId;
		this.msgId = msgId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "position_id")
	public BlPosition getBlPosition() {
		return this.blPosition;
	}

	public void setBlPosition(BlPosition blPosition) {
		this.blPosition = blPosition;
	}

	@Column(name = "from_user_name")
	public String getFromUserName() {
		return this.fromUserName;
	}

	public void setFromUserName(String fromUserName) {
		this.fromUserName = fromUserName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "msg_type", length = 10)
	public String getMsgType() {
		return this.msgType;
	}

	public void setMsgType(String msgType) {
		this.msgType = msgType;
	}

	@Column(name = "pic_url")
	public String getPicUrl() {
		return this.picUrl;
	}

	public void setPicUrl(String picUrl) {
		this.picUrl = picUrl;
	}

	@Column(name = "media_id")
	public String getMediaId() {
		return this.mediaId;
	}

	public void setMediaId(String mediaId) {
		this.mediaId = mediaId;
	}

	@Column(name = "msg_id", length = 64)
	public String getMsgId() {
		return this.msgId;
	}

	public void setMsgId(String msgId) {
		this.msgId = msgId;
	}

}
