package com.mnuo.brieflife.entity;
// Generated 2016-10-22 18:09:31 by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BlUser generated by hbm2java
 */
@Entity
@Table(name = "bl_user", catalog = "brieflife")
public class BlUser implements java.io.Serializable {
	private static final long serialVersionUID = -6031604717119726916L;
	private int id;
	private String name;
	private Date createdAt;

	public BlUser() {
	}

	public BlUser(int id) {
		this.id = id;
	}

	public BlUser(int id, String name, Date createdAt) {
		this.id = id;
		this.name = name;
		this.createdAt = createdAt;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

}
